// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBB8chcTS-kayWbGPCicjwiX5z7fe_AF5I',
    appId: '1:1019485874888:android:bd51abab0286cb3d3193fd',
    messagingSenderId: '1019485874888',
    projectId: 'fcmtest-da4e3',
    storageBucket: 'fcmtest-da4e3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD-o_qL7mFo3J5qyVO4pvIChi11QabSR68',
    appId: '1:1019485874888:ios:d50217d53b8dd60f3193fd',
    messagingSenderId: '1019485874888',
    projectId: 'fcmtest-da4e3',
    storageBucket: 'fcmtest-da4e3.firebasestorage.app',
    iosBundleId: 'com.example.fcmTestApp',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA-L5YbrnfVAmR5mZmJHukZsBXSsalqiHY',
    appId: '1:1019485874888:web:098cfa1b473930403193fd',
    messagingSenderId: '1019485874888',
    projectId: 'fcmtest-da4e3',
    authDomain: 'fcmtest-da4e3.firebaseapp.com',
    storageBucket: 'fcmtest-da4e3.firebasestorage.app',
    measurementId: 'G-8WSJZNNL8N',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD-o_qL7mFo3J5qyVO4pvIChi11QabSR68',
    appId: '1:1019485874888:ios:d50217d53b8dd60f3193fd',
    messagingSenderId: '1019485874888',
    projectId: 'fcmtest-da4e3',
    storageBucket: 'fcmtest-da4e3.firebasestorage.app',
    iosBundleId: 'com.example.fcmTestApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA-L5YbrnfVAmR5mZmJHukZsBXSsalqiHY',
    appId: '1:1019485874888:web:4e285acc31ee69a83193fd',
    messagingSenderId: '1019485874888',
    projectId: 'fcmtest-da4e3',
    authDomain: 'fcmtest-da4e3.firebaseapp.com',
    storageBucket: 'fcmtest-da4e3.firebasestorage.app',
    measurementId: 'G-X995Y6EF0T',
  );

}